description: QuadCopterFuseLageWithSensors
design_name: QuadWithCargoNew
assembly_path: "C:\\Users\\umesh\\Documents\\CreoUAVs\\TestQuadNew\\uav.asm"
creoson_host: "localhost"
creoson_port: "9056"
parameter_map: "C:\\Users\\umesh\\swri\\athens-dragstudy\\athens_dragstudy\\data\\design_zips\\TestQuadWithSensors\\archive\\result_1\\designParameters.json"
save_root: "experiments"
fdm:
  Analysis_Type: 3
  Ctrl_R: 0.1
  Flight_Path:
    - 1
    - 3
    - 4
    - 5
  Q_Angles: 1
  Q_Angular_Velocity: 1
  Q_Position: 1
  Q_Velocity: 1
  Requested_Lateral_Speed: 1
  Requested_Vertical_Speed: 19
num_samples: 10
random_seed: 42
params:
  capsule_fuselage_BOTTOM_CONNECTOR_OFFSET_LENGTH:
    min: -100
    max: 100
    components:
      - capsule_fuselage
    parameter: BOTTOM_CONNECTOR_OFFSET_LENGTH

  capsule_fuselage_BOTTOM_CONNECTOR_OFFSET_WIDTH:
    min: -100
    max: 100
    components:
      - capsule_fuselage
    parameter: BOTTOM_CONNECTOR_OFFSET_WIDTH

  capsule_fuselage_BOTTOM_CONNECTOR_ROTATION:
    min: 0
    max: 360
    components:
      - capsule_fuselage
    parameter: BOTTOM_CONNECTOR_ROTATION

  capsule_fuselage_FLOOR_CONNECTOR_1_DISP_LENGTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_1_DISP_LENGTH

  capsule_fuselage_FLOOR_CONNECTOR_1_DISP_WIDTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_1_DISP_WIDTH

  capsule_fuselage_FLOOR_CONNECTOR_2_DISP_LENGTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_1_DISP_LENGTH

  capsule_fuselage_FLOOR_CONNECTOR_2_DISP_WIDTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_2_DISP_WIDTH

  capsule_fuselage_FLOOR_CONNECTOR_3_DISP_LENGTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_3_DISP_LENGTH

  capsule_fuselage_FLOOR_CONNECTOR_3_DISP_WIDTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_3_DISP_WIDTH

  capsule_fuselage_FLOOR_CONNECTOR_4_DISP_LENGTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_4_DISP_LENGTH

  capsule_fuselage_FLOOR_CONNECTOR_4_DISP_WIDTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_4_DISP_WIDTH

  capsule_fuselage_FLOOR_CONNECTOR_5_DISP_LENGTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_5_DISP_LENGTH

  capsule_fuselage_FLOOR_CONNECTOR_5_DISP_WIDTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_5_DISP_WIDTH

  capsule_fuselage_FLOOR_CONNECTOR_6_DISP_LENGTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_6_DISP_LENGTH

  capsule_fuselage_FLOOR_CONNECTOR_6_DISP_WIDTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_6_DISP_WIDTH

  capsule_fuselage_FLOOR_CONNECTOR_7_DISP_LENGTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_7_DISP_LENGTH

  capsule_fuselage_FLOOR_CONNECTOR_7_DISP_WIDTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_7_DISP_WIDTH

  capsule_fuselage_FLOOR_CONNECTOR_8_DISP_LENGTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_8_DISP_LENGTH

  capsule_fuselage_FLOOR_CONNECTOR_8_DISP_WIDTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: FLOOR_CONNECTOR_8_DISP_WIDTH

  capsule_fuselage_FLOOR_HEIGHT:
    min: 10
    max: 50
    components:
      - capsule_fuselage
    parameter: FLOOR_HEIGHT

  capsule_fuselage_HORZ_DIAMETER:
    min: 30
    max: 500
    components:
      - capsule_fuselage
    parameter: HORZ_DIAMETER

  capsule_fuselage_TUBE_LENGTH:
    min: 0
    max: 500
    components:
      - capsule_fuselage
    parameter: TUBE_LENGTH

  capsule_fuselage_VERT_DIAMETER:
    min: 30
    max: 500
    components:
      - capsule_fuselage
    parameter: VERT_DIAMETER
